### ISSUE TITLE
Recognized Text Formatting

### ISSUE THREAD

**Issue by Solanine** [watson-developer-cloud/speech-to-text-nodejs#99] opened 2016-04-15 15:21 UTC
First, thank you so much for your work.

I have a local node system all setup and working well on a Linux VM. I cant seem to figure out why the recognized text prior to final result is being displayed as one long string. Maybe cause im tired, but it's not clear to me. I would like each word regardless of final result to be displayed separately.

Currently pre final result it looks like this:

Thequickbrownfox

I would like it to display

The quick brown fox

Regardless of whether this gets corrected/changed.

Thanks!

**Comment by nfriedly** [comment] 2016-04-15 15:28
Hi Solanine,

That does sound like a problem.. a few questions:
* Have you made any changes to the demo app? 
  * If yes, can you post your code anywhere (be sure to remove any passwords you may have added first)
* Do you experience the same behavior with out public demo? (https://speech-to-text-demo.mybluemix.net/)
* You may also want to try out our beta Speech JavaScript SDK, as it's generally easier to work with - https://github.com/watson-developer-cloud/speech-javascript-sdk/releases (there is work in progress to convert this demo to using the SDK)

**Comment by Solanine** [comment] 2016-04-15 15:53
Nathan, 

Thanks for the fast response. With the exception of changing to a secure server to deal with the getusermedia issue no, I've made no other changes. But it did this prior to using TLS as well. In fact I blew away the whole install and re-built it to make sure it was vanilla.

The demo app works as expected. I'll check out the JS SDK, but I would like to try and get this one running.. any other thoughts?  Thanks!

**Comment by nfriedly** [comment] 2016-04-15 15:55
That is really strange. Hang on a few minutes. I have a fork with an in-progress update to use the JS SDK, let me try and clean that up and have you test it.

**Comment by Solanine** [comment] 2016-04-15 16:02
Just for posterity, here is an image of what it does....  :) 
![s2t_watson](https://cloud.githubusercontent.com/assets/18486520/14567385/d88b50e6-0301-11e6-9b28-572338ae7ad3.png)

**Comment by nfriedly** [comment] 2016-04-15 16:38
Wierd. 

It seems that there have been some significant changes since I initially started the JS SDK branch.. this is going to take a bit longer than I had hoped :/

**Comment by Solanine** [comment] 2016-04-15 16:42
No rush, appreciate the help..

**Comment by nfriedly** [comment] 2017-01-13 19:21
Hey @Solanine,

Sorry this fell off the radar a while back, but we just launched the new version of the demo where this should be fixed. Please re-open if you can still reproduce the issue on the new demo.

**Closed by nfriedly** 2017-01-13 19:21 UTC
