### ISSUE TITLE
STT DEMO KWS -- Text normalization is needed for all models; all keywords are erroneously not spotted for all non-US English models

### ISSUE THREAD

**Issue by Atreilly** [watson-developer-cloud/speech-to-text-nodejs#112] opened 2016-06-22 21:36 UTC
Re: STT DEMO KWS -- Text normalization is needed for all models; all keywords are erroneously not spotted for all non-US English models. Currently, all keywords are spotted for only US English models.

When testing STT demo, via this link --> https://speech-to-text-demo-june20th.mybluemix.net/, I sighted this issue. 

For all models, (except US Engish broadband and narrowband models), when more than one keyword is entered with different casings (lowercase vs. uppercase) of the same keyword, (i.e., para, PARA) in the key word spotting box, erroneously, not all of these words are spotted. 

For this example, where text is..
"PERO QUIERO PREGUNTARLE SI SOLO EXISTEN PRODUCTOS. PARA LA PIEL PARA TRATAR EL ACNE. OH HAY OTRA FORMA DE TRATARLO. "

Expected: 
- para (2)
-  Start:  5.89    End:    6.12    Confidence: 100.0%
-  Start:  6.77    End:    7.02    Confidence: 99.9%
- PARA (2)
-  Start:  5.89    End:    6.12    Confidence: 100.0%
-  Start:  6.77    End:    7.02    Confidence: 99.9%

Actual:
para 
- PARA (2)
-  Start:  5.89    End:    6.12    Confidence: 100.0%
-  Start:  6.77    End:    7.02    Confidence: 99.9%

Please let me know if you have any questions or comments.

Alexandra

**Comment by nfriedly** [comment] 2016-06-23 20:37
Hi @Atreilly , thanks again.

I don't think there's a distinction between upper case and lower case for keyword spotting, so that's probably part of the issue. That said, I think the service should return all occurences of the keyword. @daniel-bolanos ?

**Comment by nfriedly** [comment] 2017-01-13 19:34
Looking at this again, I think I understand better. For English, keyword casing is normalized and the keyword is still spotted if the casing is different; whereas, for e.g. Spanish, keyword casing is not normalized and must match the output casing.

I'm going to notify the service team and close this, as the issue is not really specific to the demo.

**Closed by nfriedly** 2017-01-13 19:34 UTC
